- name: "Make sure podman is running and enabled"
  ansible.builtin.systemd:
    name: "podman"
    enabled: true
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: root

- name: Ensure existence of a local podman network
  containers.podman.podman_network:
    name: nextcloud_network
    net_config:
      - subnet: "10.0.1.0/24"
        gateway: "10.0.1.1"
      - subnet: "fd00:c0::/64"
        gateway: "fd00:c0::1"
    ipv6: true
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: root

- name: "Ensure pod autostart after reboot is enabled"
  ansible.builtin.systemd:
    name: podman-restart.service
    enabled: true
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: root

- name: Add docker as a container registry
  ansible.builtin.lineinfile:
    dest: "/etc/containers/registries.conf"
    line: 'unqualified-search-registries = ["docker.io"]'
    owner: root
    group: root
    mode: "0644"
    state: present
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: root
