- name: "Make sure podman is running and enabled"
  ansible.builtin.systemd:
    name: "podman"
    enabled: true
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: root

- name: Ensure existence of a local podman network
  containers.podman.podman_network:
    name: nextcloud_network
    net_config:
      - subnet: "10.0.1.0/24"
        gateway: "10.0.1.1"
      - subnet: "fd00:c0::/64"
        gateway: "fd00:c0::1"
    ipv6: true
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: "{{ podman_user }}"

- name: Create the podman.socket file
  ansible.builtin.copy:
    src: podman.socket
    dest: /usr/lib/systemd/user/podman.socket
    mode: "0644"
    owner: root
    group: root
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: root

- name: Enable podman.socket
  ansible.builtin.systemd:
    scope: user
    state: started
    name: podman.socket
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ podman_user_uid }}"
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: "{{ podman_user }}"

- name: Set DOCKER_HOST environment variable
  ansible.builtin.lineinfile:
    path: /etc/environment
    state: present
    line: "DOCKER_HOST=unix://run/user/{{ podman_user_uid }}/podman/podman.sock"
    owner: root
    group: root
    mode: "0644"
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: root

- name: "Ensure pod autostart after reboot is enabled"
  ansible.builtin.systemd:
    name: podman-restart.service
    enabled: true
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: root
