- name: Get home directory of podman user
  ansible.builtin.getent:
    database: passwd
    key: "{{ podman_user }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Set home directory var for deploy user
  ansible.builtin.set_fact:
    podman_user_home: "{{ getent_passwd[podman_user][4] }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Set uid var for deploy user
  ansible.builtin.set_fact:
    podman_user_uid: "{{ getent_passwd[podman_user][1] }}"
  ignore_errors: "{{ ansible_check_mode }}"
