---
# tasks file for nextcloud_podman_setup
- name: Get user information
  ansible.builtin.include_tasks: get_user_info.yml

- name: Ensure podman configuration
  ansible.builtin.include_tasks: podman.yml

- name: Setup data and config directories
  ansible.builtin.include_tasks: setup_directories.yml

- name: Setup mariadb
  ansible.builtin.include_tasks: mariadb.yml

- name: Setup nextcloud
  ansible.builtin.include_tasks: nextcloud.yml

- name: Reset connection to load environment variable
  ansible.builtin.meta: reset_connection
