---
# tasks file for nextcloud_podman_setup
- name: Get user information
  ansible.builtin.include_tasks:
    file: "get_user_info.yml"

- name: Configure and start container runtime
  ansible.builtin.include_tasks:
    file: "{{ ansible_distribution }}_cr_start.yml"

- name: Setup data and config directories
  ansible.builtin.include_tasks:
    file: "setup_directories.yml"

- name: Setup mariadb
  ansible.builtin.include_tasks:
    file: "mariadb.yml"

- name: Setup nextcloud
  ansible.builtin.include_tasks:
    file: "nextcloud.yml"
