- name: Create MariaDB container
  containers.podman.podman_container:
    debug: true
    conmon_pidfile: "/tmp/mariadb_conmon.pid"
    image: "{{ mariadb_image }}"
    image_strict: true
    recreate: false
    state: started
    name: "nextcloud_mariadb"
    user: "{{ podman_user_uid }}"
    userns: keep-id
    network:
      - nextcloud_network
    env:
      MYSQL_USER: "nextcloud"
      MYSQL_PASSWORD: "{{ mysql_password }}"
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      MYSQL_DATABASE: "nextcloud_db"
    volume: "{{ nextcloud_data_dir }}/mysql:/var/lib/mysql:Z"
    generate_systemd:
      path: "{{ podman_user_home }}/.config/systemd/user"
      restart_policy: always
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: "{{ podman_user }}"

- name: Wait for DB to initilize
  ansible.builtin.wait_for:
    timeout: 20

- name: MariaDB container must be started and enabled on systemd
  ansible.builtin.systemd:
    name: container-nextcloud_mariadb
    scope: user
    daemon_reload: true
    state: started
    enabled: true
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ podman_user_uid }}"
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: "{{ podman_user }}"
