- name: Remove tc.log
  ansible.builtin.file:
    path: "{{ nextcloud_data_dir }}/mysql/tc.log"
    state: absent
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: root

- name: Create MariaDB container
  containers.podman.podman_container:
    debug: true
    image: "{{ mariadb_image }}"
    image_strict: true
    detach: true
    recreate: false
    state: started
    name: "nextcloud_mariadb"
    network:
      - nextcloud_network
    env:
      MYSQL_USER: "nextcloud"
      MYSQL_PASSWORD: "{{ mysql_password }}"
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      MYSQL_DATABASE: "nextcloud_db"
    volumes:
      - "{{ nextcloud_data_dir }}/mysql:/var/lib/mysql:Z"
      - "/var/run/podman/podman.sock:/var/run/docker.sock:ro,z"
      - "/etc/localtime:/etc/localtime"
  register: mariadb_change
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: root

- name: Wait for DB to initilize
  ansible.builtin.wait_for:
    timeout: 20
  when: mariadb_change is changed
