- name: Create MariaDB container
  containers.podman.podman_container:
    debug: true
    image: "{{ mariadb_image }}"
    image_strict: true
    detach: true
    recreate: false
    state: started
    name: "nextcloud_mariadb"
    network:
      - nextcloud_network
    env:
      MYSQL_USER: "nextcloud"
      MYSQL_PASSWORD: "{{ mysql_password }}"
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      MYSQL_DATABASE: "nextcloud_db"
    volumes:
      - "{{ nextcloud_data_dir }}/mysql:/var/lib/mysql:Z"
      - "/var/run/podman/podman.sock:/var/run/docker.sock:ro,z"
      - "/etc/localtime:/etc/localtime"
    generate_systemd:
      path: "/etc/containers/systemd/"
      restart_policy: always
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: root

- name: Wait for DB to initilize
  ansible.builtin.wait_for:
    timeout: 20

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
  become: true
  become_user: root

- name: MariaDB container must be started and enabled on systemd
  ansible.builtin.systemd:
    name: container-nextcloud_mariadb
    daemon_reload: true
    state: started
    enabled: true
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: root
