- name: "Copy traefik main configuration file"
  ansible.builtin.copy:
    src: "traefik.yml"
    dest: "{{ podman_user_home }}/traefik/traefik.yml"
    mode: "0640"
  register: "traefik_base_config"

- name: "Ensure systemd socket proxy for traefik"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ podman_user_home }}/.config/systemd/user"
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
    mode: "0644"
  loop:
    - "container-traefik-proxy-80.socket"
    - "container-traefik-proxy-443.socket"
    - "container-traefik-proxy-8080.socket"
    - "container-traefik-proxy@.service"
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: "{{ podman_user }}"

- name: Systemd daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true
    scope: user
  become: true
  become_user: "{{ podman_user }}"

- name: Start and enable socket proxy
  ansible.builtin.systemd_service:
    name: "container-traefik-proxy-{{ item }}.socket"
    scope: user
    state: started
  loop:
    - "80"
    - "443"
    - "8080"
  become: true
  become_user: "{{ podman_user }}"

- name: Create traefik container
  containers.podman.podman_container:
    name: traefik
    conmon_pidfile: "/tmp/traefik_conmon.pid"
    image: "{{ traefik_image }}"
    image_strict: true
    recreate: true
    state: started
    user: "{{ podman_user_uid }}"
    userns: keep-id
    network:
      - nextcloud_network
    publish:
      # - "127.0.0.1:80:80"
      # - "127.0.0.1:443:443"
      - "127.0.0.1:8080:8080"
    volume:
      - "{{ podman_user_home }}/traefik/traefik.yml:/traefik.yml:ro,Z"
      - "{{ podman_user_home }}/traefik:/config:ro,Z"
      - "/run/user/{{ podman_user_uid }}/podman/podman.sock:/var/run/docker.sock:z"
    command:
      - --api.insecure=true
      - --providers.docker
    security_opt:
      - "label:type:container_runtime_t"
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.rule: "Host(`{{ traefik_api_url }}`)"
    generate_systemd:
      path: "{{ podman_user_home }}/.config/systemd/user"
      restart_policy: always
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ podman_user_uid }}"
  register: "traefik_creation"
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: "{{ podman_user }}"

- name: Traefik container must be started and enabled on systemd
  ansible.builtin.systemd:
    name: container-traefik
    scope: user
    daemon_reload: true
    state: started
    enabled: true
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ podman_user_uid }}"
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: "{{ podman_user }}"

- name: Configure iptables for published ports
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_ports:
      - "80"
      - "443"
      - "8080"
    jump: ACCEPT
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: root

- name: "Restart traefik if config changed and container was not newly created"
  ansible.builtin.assert:
    that: true
    quiet: true
  changed_when: true
  when:
    - traefik_creation is not changed
    - traefik_base_config is changed
  notify: "Podman: Restart traefik"
