- name: Ensure traefik config direcotry
  ansible.builtin.file:
    path: "/root/traefik"
    state: directory
    mode: "0750"
    owner: root
    group: root
  become: true
  become_user: root

- name: "Copy traefik main configuration file"
  ansible.builtin.copy:
    src: "traefik.yml"
    dest: "/root/traefik/traefik.yml"
    mode: "0640"
  become: true
  become_user: root
  register: "traefik_base_config"

- name: Create traefik container
  containers.podman.podman_container:
    name: traefik
    conmon_pidfile: "/tmp/traefik_conmon.pid"
    image: "{{ traefik_image }}"
    image_strict: true
    recreate: false
    state: started
    network:
      - nextcloud_network
    publish:
      - "80:80"
      - "443:443"
    volume:
      - "/root/traefik/traefik.yml:/traefik.yml:ro,Z"
      - "/root/traefik:/config:ro,Z"
      - "/var/run/podman/podman.sock:/var/run/docker.sock:ro,z"
      - "/etc/localtime:/etc/localtime"
    security_opt:
      - "label:type:container_runtime_t"
    labels:
      traefik.enable: true
      traefik.http.services.traefik.loadbalancer.server.port: "8080" # update to actual port
      traefik.http.routers.traefik-https.rule: Host(`api.riz-rpi-001.riz.internal`)
      traefik.http.routers.traefik-https.entrypoints: https
      traefik.http.routers.traefik_https.service: api@internal
      traefik.http.routers.traefik-https.tls: true
  register: "traefik_creation"
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: root

- name: Configure iptables for published ports
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_ports:
      - "80"
      - "443"
      - "8080"
    jump: ACCEPT
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: root

- name: "Restart traefik if config changed and container was not newly created"
  ansible.builtin.assert:
    that: true
    quiet: true
  changed_when: true
  when:
    - traefik_creation is not changed
    - traefik_base_config is changed
  notify: "Podman: Restart traefik"
