---
# Ansible managed - Do not change!
global:
  checkNewVersion: false
  sendAnonymousUsage: false

serversTransport: # disable TLS verification for backend servers
  insecureSkipVerify: true

log:
  level: "WARN"

accessLog: {}
api:
  dashboard: true
  insecure: true
ping: {}

entryPoints:
  https:
    address: ":443"
  http:
    address: ":80"
#    http:
#      redirections:
#        entryPoint:
#          to: "https"
#          scheme: "https"
#          permanent: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: "/config"
    watch: true
